-- SUPERSEDED — no-op intencional.
--
-- Esta migration era o original não-idempotente que criava `workflow_comments`
-- e adicionava `triggers.input_schema`. Esse mesmo efeito já é aplicado, de
-- forma idempotente, pelas migrations corretivas que rodam ANTES desta na ordem
-- do journal:
--   0022_trigger_input_schema  → ALTER TABLE triggers ADD COLUMN IF NOT EXISTS input_schema
--   0023_workflow_comments     → CREATE TABLE IF NOT EXISTS workflow_comments (+ FKs/índices guardados)
--
-- Mantida no journal (não removida) para não alterar o histórico de bancos já
-- migrados — o migrator gateia por `when`, então bancos existentes nunca a
-- reaplicam e esta edição lhes é invisível. Em bancos novos ela vira no-op
-- porque 0022/0023 já criaram tudo. Colidia antes com "relation
-- workflow_comments already exists" / "column input_schema already exists".
SELECT 1;
